import "./globals.css";

import Image from "next/image";
import { MazzardLRegular } from "../utils/fonts";
import type { Metadata } from "next";
import Navbar from "../components/Navbar";
import Provider from "./provider";
import { ReactNode } from "react";
import logo from "@/public/logo-2.png";

// import logo from "@/public/logo.png";

// export async function generateMetadata({
//   params,
// }: {
//   params: { locale: string };
// }) {
//   const { locale } = await params;

//   let title, description, keywords;

//   if (locale === "bg") {
//     title = "Bar The Post | barthepost.bg";
//     description =
//       "Потопи се в света на миксологията, където зад всяка поръчка стои почеркът на нашите бармани... а коктейлите разказват истории, които ще искаш да чуеш отново и отново...";
//     keywords = [
//       "Пощата",
//       "бар Пощата",
//       "ППощата Пловдив",
//       "бар Пловдив",
//       "Пловдив",
//       "коктейл бар Пловдив",
//       "парти",
//       "коктейли",
//       "атмосфера",
//       "нощен живот",
//       "bar The Post",
//       "The Post Plovdiv",
//       "bar Plovdiv",
//       "Plovdiv",
//       "cocktail bar Plovdiv",
//       "parties",
//       "cocktails",
//       "vibe",
//       "nightlife",
//     ];
//   } else if (locale === "en") {
//     title = "Bar The Post | barthepost.bg";
//     description =
//       "Immerse yourself in the world of mixology, where every order carries the signature of our bartenders...and the cocktails tell stories you’ll want to hear again and again...";
//     keywords = [
//       "The Post",
//       "bar The Post",
//       "The Post Plovdiv",
//       "bar Plovdiv",
//       "Plovdiv",
//       "cocktail bar Plovdiv",
//       "parties",
//       "cocktails",
//       "vibe",
//       "nightlife",
//     ];
//   }

//   const alternates = {
//     canonical: locale === "en" ? "/en" : "/",
//     languages: {
//       bg: "/bg",
//       en: "/en",
//     },
//   };

//   const metadataBase = new URL("https://barthepost.bg");

//   return {
//     title,
//     description,
//     keywords,
//     alternates,
//     metadataBase,
//   };
// }

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: {
  children: ReactNode;
  params: Promise<{ locale: string }>;
}) {
  const { locale } = await params;

  return (
    <html lang={locale}>
      <body className={`${MazzardLRegular.className} antialiased`}>
        <Provider locale={Promise.resolve({ locale })}>
          <div className="hidden absolute top-8 w-full md:flex justify-center items-center z-50">
            <Image
              src={logo}
              alt="Logo"
              // width={112}
              width={260}
              priority
              // style={{ backgroundColor: "rgba(0, 0, 0, 0.7)" }}
              // className="p-4 rounded-full"
            />
          </div>

          {children}
          <Navbar />
        </Provider>
      </body>
    </html>
  );
}
